-- ============================================================
--  TransitFlow PostgreSQL Schema
--  Seed data is loaded separately by: python skeleton/seed_postgres.py
--
--  TWO ROLES:
--    1. Relational  → dual-network transit data
--    2. Vector      → policy documents for RAG (provided — do not modify)
--
--  DELETE STRATEGY: Soft delete throughout.
--    - users:                 is_active = FALSE  (never physically deleted)
--    - national_rail_bookings / metro_travels: status = 'cancelled'
--    - Rationale: preserves audit trail and payment history; hard deletes
--      would cascade and destroy financial records.
-- ============================================================

-- ============================================================
--  RELATIONAL SCHEMA
-- ============================================================

-- 1. Metro Stations
--    PK: VARCHAR(10) — natural key from mock data (e.g. "MS01").
--    VARCHAR chosen over SERIAL/UUID because IDs are human-readable
--    codes defined by the operator, not generated by the database.
CREATE TABLE IF NOT EXISTS metro_stations (
    -- VARCHAR natural key: station codes are operator-assigned, not DB-generated
    station_id                       VARCHAR(10)  PRIMARY KEY,
    name                             TEXT         NOT NULL,
    lines                            JSONB        NOT NULL,  -- e.g. ["M1","M2"] — small, read-only list; no FK needed
    is_interchange_metro             BOOLEAN      DEFAULT FALSE,
    is_interchange_national_rail     BOOLEAN      DEFAULT FALSE,
    -- No FK here: cross-network reference resolved at query time to avoid circular dependency
    interchange_nr_station_id        VARCHAR(10)
);

-- 2. National Rail Stations
--    PK: VARCHAR(10) — same rationale as metro_stations.
CREATE TABLE IF NOT EXISTS national_rail_stations (
    station_id                       VARCHAR(10)  PRIMARY KEY,
    name                             TEXT         NOT NULL,
    lines                            JSONB        NOT NULL,  -- e.g. ["NR1","NR2"]
    is_interchange_metro             BOOLEAN      DEFAULT FALSE,
    interchange_metro_station_id     VARCHAR(10)
);

-- 3. Metro Schedules
--    PK: VARCHAR(20) — operator-assigned schedule codes (e.g. "MS_SCH01").
--    stops_in_order and operates_on are normalised into separate junction
--    tables (metro_schedule_stops, metro_schedule_operates_on) below.
CREATE TABLE IF NOT EXISTS metro_schedules (
    schedule_id            VARCHAR(20)   PRIMARY KEY,
    line                   VARCHAR(5)    NOT NULL,
    direction              VARCHAR(20),
    -- RESTRICT: do not delete a station that still has schedules running through it
    origin_station_id      VARCHAR(10)   REFERENCES metro_stations(station_id) ON DELETE RESTRICT,
    destination_station_id VARCHAR(10)   REFERENCES metro_stations(station_id) ON DELETE RESTRICT,
    first_train_time       TIME,
    last_train_time        TIME,
    base_fare_usd          NUMERIC(6,2)  NOT NULL,  -- NUMERIC: exact decimal arithmetic for money
    per_stop_rate_usd      NUMERIC(6,2)  NOT NULL,
    frequency_min          INTEGER
);

-- 3a. Metro Schedule Stops (junction table — normalised stop sequence)
--     Separating stops into their own table achieves 3NF: stop_order and
--     travel_time are functionally dependent on (schedule_id, station_id),
--     not on schedule_id alone.
CREATE TABLE IF NOT EXISTS metro_schedule_stops (
    schedule_id             VARCHAR(20)  NOT NULL REFERENCES metro_schedules(schedule_id) ON DELETE CASCADE,
    station_id              VARCHAR(10)  NOT NULL REFERENCES metro_stations(station_id) ON DELETE RESTRICT,
    stop_order              INTEGER      NOT NULL,  -- 0-based position in route
    travel_time_from_origin INTEGER      NOT NULL,  -- minutes from first stop
    -- Composite PK on (schedule_id, station_id): each station appears at most once per schedule;
    -- no surrogate key needed because the natural pair is already unique and stable.
    PRIMARY KEY (schedule_id, station_id)
);

-- 3b. Metro Schedule Operating Days (junction table)
--     Separated to avoid repeating schedule data per day (2NF violation if inlined).
CREATE TABLE IF NOT EXISTS metro_schedule_operates_on (
    schedule_id  VARCHAR(20)  NOT NULL REFERENCES metro_schedules(schedule_id) ON DELETE CASCADE,
    day          VARCHAR(5)   NOT NULL,  -- 'mon','tue','wed','thu','fri','sat','sun'
    -- Composite PK: a schedule runs on each day at most once; the pair is the natural unique key.
    PRIMARY KEY (schedule_id, day)
);

-- 4. National Rail Schedules
--    PK: VARCHAR(20) — operator-assigned codes (e.g. "NR_SCH01").
CREATE TABLE IF NOT EXISTS national_rail_schedules (
    schedule_id            VARCHAR(20)   PRIMARY KEY,
    line                   VARCHAR(5)    NOT NULL,
    service_type           VARCHAR(20)   NOT NULL,  -- 'normal' or 'express'
    direction              VARCHAR(20),
    origin_station_id      VARCHAR(10)   REFERENCES national_rail_stations(station_id) ON DELETE RESTRICT,
    destination_station_id VARCHAR(10)   REFERENCES national_rail_stations(station_id) ON DELETE RESTRICT,
    first_train_time       TIME,
    last_train_time        TIME,
    -- Two fare classes stored as separate columns (not a sub-table) because
    -- there are exactly two classes and fare lookup always needs both for comparison.
    std_base_fare_usd      NUMERIC(6,2),
    std_per_stop_rate_usd  NUMERIC(6,2),
    first_base_fare_usd    NUMERIC(6,2),
    first_per_stop_rate_usd NUMERIC(6,2),
    frequency_min          INTEGER
);

-- 4a. National Rail Schedule Stops (junction table — normalised stop sequence)
--     Same 3NF rationale as metro_schedule_stops.
CREATE TABLE IF NOT EXISTS national_rail_schedule_stops (
    schedule_id             VARCHAR(20)  NOT NULL REFERENCES national_rail_schedules(schedule_id) ON DELETE CASCADE,
    station_id              VARCHAR(10)  NOT NULL REFERENCES national_rail_stations(station_id) ON DELETE RESTRICT,
    stop_order              INTEGER      NOT NULL,
    travel_time_from_origin INTEGER      NOT NULL,
    -- Composite PK: same rationale as metro_schedule_stops — natural pair is unique and stable.
    PRIMARY KEY (schedule_id, station_id)
);

-- 4b. National Rail Schedule Operating Days (junction table)
CREATE TABLE IF NOT EXISTS national_rail_schedule_operates_on (
    schedule_id  VARCHAR(20)  NOT NULL REFERENCES national_rail_schedules(schedule_id) ON DELETE CASCADE,
    day          VARCHAR(5)   NOT NULL,
    -- Composite PK: same rationale as metro_schedule_operates_on.
    PRIMARY KEY (schedule_id, day)
);

-- 5. Seat Layouts (one row per physical seat)
--    Flat table — one row per seat avoids nested arrays and makes
--    seat availability queries a simple NOT IN subquery.
CREATE TABLE IF NOT EXISTS seat_layouts (
    -- seat_id is only unique within a schedule (e.g. "A01" exists in both NR_SCH01 and NR_SCH02),
    -- so a composite PK on (schedule_id, seat_id) is used instead of a surrogate key.
    seat_id      VARCHAR(10)  NOT NULL,
    schedule_id  VARCHAR(20)  NOT NULL REFERENCES national_rail_schedules(schedule_id) ON DELETE CASCADE,
    coach        VARCHAR(5)   NOT NULL,
    fare_class   VARCHAR(20)  NOT NULL,  -- 'standard' or 'first'
    row          INTEGER      NOT NULL,
    col          VARCHAR(5)   NOT NULL,
    PRIMARY KEY (schedule_id, seat_id)
);

-- 6. Users
--    PK: VARCHAR(10) — operator-assigned IDs (e.g. "RU01").
--    Soft delete: is_active = FALSE preserves booking/payment history.
--    Password is NOT stored here — see user_credentials table.
CREATE TABLE IF NOT EXISTS users (
    user_id         VARCHAR(10)   PRIMARY KEY,
    full_name       TEXT          NOT NULL,
    email           VARCHAR(200)  UNIQUE NOT NULL,
    phone           VARCHAR(20),
    date_of_birth   DATE,
    secret_question TEXT,
    secret_answer   TEXT,
    registered_at   TIMESTAMPTZ   DEFAULT NOW(),
    -- Soft delete flag — set FALSE instead of deleting to preserve audit trail
    is_active       BOOLEAN       DEFAULT TRUE
);

-- 6b. User Credentials
--     Password hash and salt stored in a SEPARATE table from user profile data.
--     Rationale: principle of least privilege — queries that only need profile
--     info (name, email) never touch credential data. bcrypt hash includes the
--     cost factor; salt stored explicitly for auditability.
CREATE TABLE IF NOT EXISTS user_credentials (
    -- CASCADE: deleting a user also removes their credentials
    user_id       VARCHAR(10)  PRIMARY KEY REFERENCES users(user_id) ON DELETE CASCADE,
    password_hash TEXT         NOT NULL,  -- bcrypt hash (includes cost factor)
    salt          TEXT         NOT NULL,  -- bcrypt-generated random salt per user
    created_at    TIMESTAMPTZ  DEFAULT NOW(),
    updated_at    TIMESTAMPTZ  DEFAULT NOW()
);

-- 7. National Rail Bookings
--    Soft delete: status = 'cancelled' — booking record retained for payment history.
CREATE TABLE IF NOT EXISTS national_rail_bookings (
    -- PK: VARCHAR with app-generated prefix "BK-" for human readability in receipts
    booking_id              VARCHAR(20)  PRIMARY KEY,
    -- RESTRICT: do not delete users or stations that have bookings
    user_id                 VARCHAR(10)  NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
    schedule_id             VARCHAR(20)  NOT NULL REFERENCES national_rail_schedules(schedule_id) ON DELETE RESTRICT,
    origin_station_id       VARCHAR(10)  NOT NULL REFERENCES national_rail_stations(station_id) ON DELETE RESTRICT,
    destination_station_id  VARCHAR(10)  NOT NULL REFERENCES national_rail_stations(station_id) ON DELETE RESTRICT,
    travel_date             DATE         NOT NULL,
    departure_time          TIME,
    ticket_type             VARCHAR(20)  NOT NULL,  -- 'single' or 'return'
    fare_class              VARCHAR(20)  NOT NULL,  -- 'standard' or 'first'
    coach                   VARCHAR(5),
    seat_id                 VARCHAR(10),
    stops_travelled         INTEGER,
    amount_usd              NUMERIC(8,2) NOT NULL,
    -- Soft delete: 'confirmed' → 'cancelled'; 'completed' for past journeys
    status                  VARCHAR(20)  NOT NULL DEFAULT 'confirmed',
    booked_at               TIMESTAMPTZ  DEFAULT NOW(),
    travelled_at            TIMESTAMPTZ
);

-- 8. Metro Travel History
--    Soft delete: status column — same strategy as national_rail_bookings.
CREATE TABLE IF NOT EXISTS metro_travels (
    -- PK: app-generated VARCHAR ID with "MT" prefix for human-readable trip references.
    trip_id                 VARCHAR(20)  PRIMARY KEY,
    user_id                 VARCHAR(10)  NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
    schedule_id             VARCHAR(20)  NOT NULL REFERENCES metro_schedules(schedule_id) ON DELETE RESTRICT,
    origin_station_id       VARCHAR(10)  NOT NULL REFERENCES metro_stations(station_id) ON DELETE RESTRICT,
    destination_station_id  VARCHAR(10)  NOT NULL REFERENCES metro_stations(station_id) ON DELETE RESTRICT,
    travel_date             DATE         NOT NULL,
    ticket_type             VARCHAR(20)  NOT NULL,  -- 'single' or 'day_pass'
    day_pass_ref            VARCHAR(20),
    stops_travelled         INTEGER,
    amount_usd              NUMERIC(8,2) NOT NULL,
    status                  VARCHAR(20)  NOT NULL DEFAULT 'completed',
    purchased_at            TIMESTAMPTZ  DEFAULT NOW(),
    travelled_at            TIMESTAMPTZ
);

-- 9. Payments
--    booking_id is intentionally NOT a FK — it is polymorphic:
--    it can reference national_rail_bookings (BK-***) or metro_travels (MT***).
--    PostgreSQL does not support polymorphic FKs, so referential integrity
--    is enforced at the application layer in execute_booking / execute_cancellation.
CREATE TABLE IF NOT EXISTS payments (
    -- PK: app-generated VARCHAR ID with "PM-" prefix; matches the style of booking_id
    -- for consistent human-readable references across all financial records.
    payment_id   VARCHAR(20)  PRIMARY KEY,
    booking_id   VARCHAR(20)  NOT NULL,   -- polymorphic: BK-*** or MT***
    amount_usd   NUMERIC(8,2) NOT NULL,
    method       VARCHAR(50),
    status       VARCHAR(20)  NOT NULL DEFAULT 'paid',
    paid_at      TIMESTAMPTZ  DEFAULT NOW()
);

-- 10. Feedback
--     booking_id is polymorphic (same reason as payments — no FK).
CREATE TABLE IF NOT EXISTS feedback (
    -- PK: app-generated VARCHAR ID; VARCHAR over SERIAL so IDs are portable across environments.
    feedback_id   VARCHAR(20)  PRIMARY KEY,
    booking_id    VARCHAR(20)  NOT NULL,
    user_id       VARCHAR(10)  NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
    rating        INTEGER      CHECK (rating BETWEEN 1 AND 5),
    comment       TEXT,
    submitted_at  TIMESTAMPTZ  DEFAULT NOW()
);


-- ============================================================
--  VECTOR SCHEMA  (RAG / Help Desk) — do not modify
-- ============================================================

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS policy_documents (
    id          SERIAL       PRIMARY KEY,
    title       VARCHAR(200) NOT NULL,
    category    VARCHAR(50)  NOT NULL,  -- 'refund', 'booking', 'conduct'
    content     TEXT         NOT NULL,
    -- 768-dim  → Ollama nomic-embed-text (default)
    -- 3072-dim → Gemini gemini-embedding-001
    -- If you switch LLM_PROVIDER to gemini, change to vector(3072) and reset the database.
    embedding   vector(768),
    source_file VARCHAR(200),
    created_at  TIMESTAMPTZ  DEFAULT NOW()
);

-- Index for fast cosine similarity search
CREATE INDEX IF NOT EXISTS policy_documents_embedding_idx ON policy_documents USING hnsw (embedding vector_cosine_ops);
